### ISSUE TITLE
Filehandler.py in desperate need of ricing

### ISSUE THREAD

**Issue by Eanilsen** [Eanilsen/RPGHelper#15]
Could someone qualified help me make the filehandler look good? It is almost ready for implementation with develop.

Edit: This is regarding the branch feature-save-function

**Comment by simenfuglestad** [comment]
I've prepared a restructure of filehandler.py in feature-save-function. Would you prefer me pushing directly or do you want a separate branch?

**Comment by Eanilsen** [comment]
Just push directly to the branch. I trust your judgment!

**Comment by simenfuglestad** [comment]
Changes are now pushed. I'll leave it to you to review the file and close the issue if you are content.
