### ISSUE TITLE
Character sheet design

### ISSUE THREAD

**Issue by Eanilsen** [Eanilsen/RPGHelper#21]
How about something like this? This is minimal, but still has the detail needed for proper play.

Edit: Forgot the link. [Click me!](https://app.roll20.net/sheet-previews/pathfindersimple.png?1464293267%3E%3Cdiv%20class=)

**Comment by simenfuglestad** [comment]
I approve, this sheet looks nice.

**Comment by Jorghg** [comment]
The pathfinder sheet looks like a good template! 
Will we solve this as planned with different boxes. OR just put everything in one sheet? Solving the multi-box solution might be a bit time consuming. When I imagine it would be faster to make the sheet one "box" Where mulit window, would be a more  of a "if we have time feature". any thoughts ?

**Comment by simenfuglestad** [comment]
I want to suggest categorically dividing parts of the sheet into tabbed panes. Easy to implement and gives a good overview without flooding the screen.
