### ISSUE TITLE
Nose2 testing framework

### ISSUE THREAD

**Issue by Eanilsen** [Eanilsen/RPGHelper#6]
What do you guys think about implementing [nose2](https://nose2.readthedocs.org/en/latest/index.html) as a testing framework? It took over for [nose](http://nose.readthedocs.org/en/latest/) when that got deprecated. [Travis CI](https://travis-ci.org/) needs a testing framework to work and I think nose2, and even the old nose to be honest, will be the right tool for the job.

**Comment by Jeyloh** [comment]
I support the usage of nose/nose2 as testing framework for github Travis C. As I understand, we'll add test files under directory 'tests' named "test_ui_controller". Cheers

**Comment by simenfuglestad** [comment]
Considering [already existing](https://kivy.org/docs/contribute-unittest.html) tests supplied with kivy, I suggest we go for nose.

**Comment by Jorghg** [comment]
y

**Comment by jondam93** [comment]
Looks good!

**Comment by Eanilsen** [comment]
I think we will go with the old nose because of the already existing integration with both kivy and Travis CI.
